"""
How to print arabic in python (S.O.): https://stackoverflow.com/questions/41243215/how-to-print-arabic-text-correctly-in-python
arabic-reshaper (github): https://github.com/mpcabd/python-arabic-reshaper/
python bidi (github): https://github.com/MeirKriheli/python-bidi
print on same line (S.O.): https://stackoverflow.com/questions/20544584/python-print-on-same-line-after-sleep
json indexing: https://www.codingem.com/reading-a-json-file-in-python/
advanced vscode: https://realpython.com/advanced-visual-studio-code-python/#setting-up-your-terminal
"""
import arabic_reshaper
from bidi.algorithm import get_display
import sys
import time
import json

"""
default size setting for terminal
"terminal.integrated.fontSize": 12
"""

with open("/Users/walkerhutchinson/Library/Application Support/Code/User/settings.json", "r") as jsonFile:
    data = json.load(jsonFile)
data["terminal.integrated.fontSize"] = 40
with open("/Users/walkerhutchinson/Library/Application Support/Code/User/settings.json", "w") as jsonFile:
    json.dump(data, jsonFile, indent=4)

vocabPairs = {
    "door":"باب", 
    "class":"صفر",
    "room":"غرفة",
    "building":"بناء",
    "window":"سباك",
    "office":"مكتب",
    "library":"مكتبة",
    "sun":"شمس",
    "paper":"ورقة",
    "newspaper":"حريدة",
    "moon":"قمر",
    "word":"كلمة",
    "maths":"رياضيات",
    "strawberry":"فراولة",
    "number":"رقم",
    "breakfeast":"فطور",
    "eggs":"بيض",
    "juice":"عصر",
    "apple":"تفاح",
    "sport":"رياضة",
    "street":"شارع",
    "key":"مفتاح",
    "car":"سيارة",
    "professor":"استاذ",
    "bicycle":"دراخة",
    "picture":"صورة",
    "wall":"جدار",
    "phone":"هاتف",
    "table":"طاولة",
    "chair":"كرسي",
    "clock":"ساعة",
    "notebook":"دفتر",
    "pen":"قلم",
    "book":"كتاب",
    "board":"",
    "ceiling":"سقف",
    "ground":"ارض",
    "class":"صف",
    "shirt":"قميس",
    "ring":"خاتم",
    "pants":"سروال",
    "bag":"محفض",
    "key":"مفتاح",
    "glasses":"نضارة",
    "student":"طالب",
    "computer":"حاسوب",
    "backpack":"حقيبة",
    "TV":"تلفز",
    "thing":"شيء",
    "every":"كل",
    "drink":"شرب",
    "tea":"شاي",
    "coffee":"قهوة",
    "water":"ماء",
    "today":"يوم",
    "city":"مدينة",
    "language":"لغة",
    "arabic":"عربي",
    "english":"الانجليزنة",
    "name":"اسم",
    "light":"نور",
    "morning":"صباح",
    "love":"احب",
    "eat":"اكل",
    "drink":"اشرب",
    "church":"كنيسة",
    "Japenese":"يابانية",
    "studying":"دراسة",
    "christian":"مسيحية",
    "town":"بلدة",
    "address":"عنوان",
    "appartment":"شقة",
    "live":"اسكن",
    "thanks":"شكرا",
    "your welcome":"عفوا",
    "know":"عرف",
    "banna":"موز",
    "strawberry":"فراولة",
    "only":"فقط",
    "berry":"توت",
    "mountain":"جبل",
    "crown":"تاج",
    "bear":"دب",
    "dune":"كثيب",
    "snow":"ثلج",
    "artist":"فنان",
    "cotton":"قطن",
    "athlete":"رياصت",
    "strong":"فوي",
    "yes":"نعم",
    "stand up":"قف",
    "news":"خنر",
    "little":"قليلا",
    "lots":"كتيرا",
    "ruler":"مستطرة",
    "homeland":"وطن",
    "family":"عانلة",
    "habit":"عادة",
    "fact":"عادة",
    "currently":"حقيقة",
    "vacation(1)":"اجاضر",
    "vacation(2)":"اجازة",
    "zero":"",
    "one":"",
    "two":"",
    "three":"",
    "four":"",
    "five":"",
    "six":"",
    "seven":"",
    "eight":"",
    "nine":"",
    "nine":"",
    "year":"السنة",
    "month":"الشهر",
    "day":"اليوم",
    "Saturday":"السبت",
    "Sunday":"الاحد",
    "Monday":"الاثنين",
    "Tuesday":"التلاثة",
    "Wednesday":"الاربعة",
    "Thursday":"الخميس",
    "Friday":"الخمعة",
    "10":"",
    "brother":"اح",
    "sister":"اخت",
    "boy":"ولد",
    "girl":"بنت",
    "dad":"ان",
    "mother":"ام",
    "grandfather":"جد",
    "grandmother":"جدة",
    "middle of":"نين",
    "on":"علع",
    "in":"في",
    "in front of":"امام",
    "behind":"خاف",
    "over":"فوق",
    "under":"نحت",
    "next to":"بجانب",
    "where":"اين",
    "from":"من",
    "who":"من",
    "have":"عند",
    "opening":"نافذة",
    "y or x":"ـ ام ـ",
    "many":"عدة",
    "how many":"كم ـ",
    "what":"ما",
    "if":"اذا",
    "how":"كيف",
    "and":"و",
    "when":"متى",
    "to":"ان",
    "busy":"مشغول",
    "very":"جدا",
    "know":"اعرف",
    "Beauty be to God":"ماشاءلله",
    "Praise be to God":"الحمد لله",
    "God Knows":"الله أعلم",
    "good morning":"صباح الخير",
    "hello (religious)":"سلام عليكم",
    "hello (formal)":"مارحبن",
    "hello (casual)":"أهلا",
    "college":"جامعة",
    "playground":"ملعب",
    "swimming pool":"مسبح",
    "lab":"لغوي",
    "school of":"كلية",
    "school of sciences":"كلية العلوم",
    "school of law":"كلية الحقوق",
    "school of litature":"كلية اللاداب",
    "school of engeneering":"كلية هندسة",
    "school of medicine":"كليةالصب",
    "school of trading":"كلية التجارة",
    "history":"تاريخ",
    "biology":"احياء",
    "physics":"فيزياء",
    "chemistry":"كيمياء",
    "true":"صواب",
    "false":"خطا",
    "materials":"مواد",
    "now":"الان",
    "I":"انا",
    "We":"نحن",
    "You (m)":"انت",
    "You (f)":"انت",
    "You all":"انتم",
    "He":"هو",
    "She":"هي",
    "Them":"هم",
    "year old":"عاما",
    "age":"عمر",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    }


for x in range(len(vocabPairs)):
    dictKeysToList = list(vocabPairs)
    dictValuesToList = list(vocabPairs.values())

    text_to_be_reshaped = list(dictValuesToList)
    reshaped_text = arabic_reshaper.reshape(text_to_be_reshaped[x]) # correct its shape
    bidi_text = get_display(reshaped_text) # correct its direction
    
    print(dictKeysToList[x],"", end="")
    sys.stdout.flush()
    time.sleep(1.5)
    print(bidi_text)

    time.sleep(1)
    print()
    time.sleep(1)


with open("/Users/walkerhutchinson/Library/Application Support/Code/User/settings.json", "r") as jsonFile:
    data = json.load(jsonFile)
data["terminal.integrated.fontSize"] = 12
with open("/Users/walkerhutchinson/Library/Application Support/Code/User/settings.json", "w") as jsonFile:
    json.dump(data, jsonFile, indent=4)